services:
  doppelganger-scraper:
    build: .
    volumes:
      - ./crawls:/app/crawls
      - ./images:/app/images
      - ./logs:/app/logs
      - ./profile_urls.txt:/app/profile_urls.txt:ro
    environment:
      - SCRAPY_SETTINGS_MODULE=doppelganger.settings
      - PYTHONPATH=/app
    networks:
      - scraper-network
    depends_on:
      - camoufox-server
    healthcheck:
      test: ["CMD", "python", "-c", "import scrapy; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3

  camoufox-scraper:
    build: .
    volumes:
      - ./crawls:/app/crawls
      - ./images:/app/images
      - ./logs:/app/logs
      - ./profile_urls.txt:/app/profile_urls.txt:ro
    environment:
      - SCRAPY_SETTINGS_MODULE=doppelganger.settings
      - PYTHONPATH=/app
      - CAMOUFOX_ENABLED=true
      - CAMOUFOX_HOST=camoufox-server
      - CAMOUFOX_PORT=4444
      - DISPLAY=:99
    networks:
      - scraper-network
    depends_on:
      - camoufox-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://camoufox-server:4444/wd/hub/status", "||", "exit", "1"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s

  camoufox-server:
    image: selenium/standalone-firefox:latest
    ports:
      - "9224:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_OPTS="--log-level INFO"
    shm_size: 2gb
    networks:
      - scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  scraper-monitor:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./logs:/usr/share/nginx/html/logs:ro
      - ./crawls:/usr/share/nginx/html/crawls:ro
      - ./images:/usr/share/nginx/html/images:ro
    networks:
      - scraper-network
    profiles:
      - monitoring

networks:
  scraper-network:
    driver: bridge

volumes:
  scraper-data:
    driver: local

